name: CD
on:
  push:
    branches: [main]

env:
  REPO: ${{ github.repository_owner }}

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO
        run: |
            echo "REPO=${REPO,,}" >> $GITHUB_ENV
      - name: Build and push for master
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}/wallet-back:latest-stable

